import './globals/globals.css'
import { Libre_Franklin } from 'next/font/google'

const libre_franklin = Libre_Franklin({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={libre_franklin.className}>{children}</body>
    </html>
  )
}
